tap_install:
    sensitive_values:
        shared:
            image_registry:
                password: ENC[AES256_GCM,data:kxLvaTXDxhFQI2D5,iv:+OKbPt+5bJCJNZoHAXVQFf2ABJ5WauZnKSd8r/lZU6o=,tag:W0t+yVkBiXxe8K+OVPHhGQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k7j8gdvurdtgsxegr50can3682yrptcucykleerh8kqxqqdteypscjpgya
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6cStiVjJHNEx0Y1h3SVdD
            QWI0OVRlZTRGcC85OVNaK1dFQkxuVXFWZzBJCkR3MkRNWUJqZUJreVhpbnhKT2tL
            Ly9JbFR5bXE2V1NyYWtYVlZoL2lIMTAKLS0tIE8velVlVjJaZ2lsc0hKVS95Y2dF
            SEV5WkZWRVA4QkZuckRYa1JnVUZGTWcKPv+3EYHNPESQBjutCw4y7jL/D49xHsCc
            3FsiWDhsGF7a5u1duOOQilnfq6rDQ/D8C+gCH0EklghnWNz+/iiP9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-17T13:29:41Z"
    mac: ENC[AES256_GCM,data:wfR3P/INXkJHJguEPxYf175Ih5L4IFysMx1pJFoxe8JX/vqCTzF5ey4Mn2yAdQpKhL5GdxCdf8cmWWHYBLKAaB1mK5N098rI/GxFB14EgItuM0i4avU1EgtEUcPAI+JyRkGy39gaDoVg1tr++/OZG1tg5VNL3E3R8e3e3CgU13I=,iv:yvcFHQ6L3RftMJk5leTZ+DRviB6DQ3/YXLp312ywaus=,tag:uoZO3nfUp90VJwQhJcynZQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
